# Generated by Django 3.0.5 on 2021-03-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homenotification',
            options={'verbose_name': 'Home Page Notification'},
        ),
    ]
