# Generated by Django 3.0.5 on 2020-05-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_completion'),
        ('zoom', '0002_auto_20200518_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom',
            name='courses',
            field=models.ForeignKey(default='dd390af4-07f1-4597-b48a-f585fd79289d', on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
