# Generated by Django 3.0.5 on 2020-06-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200612_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses/Classe'},
        ),
    ]
