# Generated by Django 3.0.5 on 2021-04-06 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20200627_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
