# Generated by Django 3.0.5 on 2020-05-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zoom',
        ),
    ]
