# Generated by Django 3.0.5 on 2020-05-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_completion'),
        ('student', '0002_delete_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='courses',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
