# Generated by Django 3.0.5 on 2020-05-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_completion'),
        ('student', '0004_auto_20200522_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='courses',
            field=models.ForeignKey(default='dd390af4-07f1-4597-b48a-f585fd79289d', on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
