# Generated by Django 3.0.5 on 2020-05-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_post_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course_id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=255),
        ),
    ]
