# Generated by Django 3.0.5 on 2020-06-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200612_1421'),
        ('student', '0013_welcomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('link', models.CharField(default='', max_length=500)),
                ('courses', models.ForeignKey(default='dd390af4-07f1-4597-b48a-f585fd79289d', on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
        ),
    ]
