# Generated by Django 3.0.5 on 2020-06-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200614_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
    ]
