# Generated by Django 3.0.5 on 2021-03-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_quiz_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
