# Generated by Django 3.0.5 on 2021-04-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20210408_1716'),
        ('student', '0020_delete_quiz'),
    ]

    operations = [
    ]
