# Generated by Django 3.0.5 on 2021-03-07 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_discussions', to='discussion_board.Discussion'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
