# Generated by Django 3.0.5 on 2021-03-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0006_auto_20210307_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on', '-up_vote_count']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-up_vote_count']},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='slug',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='up_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
