# Generated by Django 3.0.5 on 2020-06-27 22:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_connect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={'verbose_name': 'Connect Page'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Lecture'},
        ),
        migrations.AlterModelOptions(
            name='readingmaterial',
            options={'verbose_name': 'Reading Material'},
        ),
        migrations.AlterModelOptions(
            name='welcomepage',
            options={'verbose_name': 'Welcome Pages/Home Page'},
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='link',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='welcomepage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
