# Generated by Django 3.0.5 on 2020-06-28 18:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200627_1511'),
        ('student', '0017_auto_20200627_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('courses', models.ForeignKey(default='dd390af4-07f1-4597-b48a-f585fd79289d', on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'verbose_name': 'Quiz Page',
            },
        ),
    ]
