# Generated by Django 3.0.5 on 2022-04-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20220314_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='std_image',
            field=models.ImageField(default='default_pfp.jpg', upload_to='profiles/'),
        ),
    ]
