# Generated by Django 3.0.5 on 2022-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_profile_std_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='std_image',
            field=models.ImageField(default='default_pfp.jpg', upload_to='upload/'),
        ),
    ]
