# Generated by Django 3.0.5 on 2022-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20220404_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='std_image',
            field=models.ImageField(default='default_pfp.jpg', upload_to='profiles/'),
        ),
    ]
