# Generated by Django 3.0.5 on 2022-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20220404_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='std_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
