# Generated by Django 3.0.5 on 2022-04-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20220404_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='std_image',
            new_name='profile_image',
        ),
    ]
