# Generated by Django 3.0.5 on 2022-04-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_auto_20220414_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_pfp.jpg', upload_to='profiles/'),
        ),
    ]
