# Generated by Django 3.0.5 on 2022-04-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20220414_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/default_image.jpg', upload_to='profiles/'),
        ),
    ]
